change dockerfile

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -21,19 +21,29 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      # Step 3: Build the Docker image
+      # Step 3: Verify the existence of the JAR file
+      - name: Verify JAR file exists
+        run: |
+          # Check if the JAR file exists in the target directory
+          if [ ! -f target/lorabackend-*.jar ]; then
+            echo "JAR file not found in target directory. Exiting."
+            exit 1
+          fi
+          echo "JAR file found: $(ls target/lorabackend-*.jar)"
+      
+      # Step 4: Build the Docker image
       - name: Build Docker Image
         run: |
           docker build -t seifmsd464325/lorabackend:latest .
 
-      # Step 4: Log in to Docker Hub
+      # Step 5: Log in to Docker Hub
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 5: Push the Docker image to Docker Hub
+      # Step 6: Push the Docker image to Docker Hub
       - name: Push Docker Image
         run: |
           docker push seifmsd464325/lorabackend:latest
